### ISSUE TITLE
关于Pr

### ISSUE THREAD

**Issue by XuanRanDev** [KitsunePie/QAssistant#13]
想为QNotfiedX贡献一下自己的代码，请问QNotifiedX是否仍然会和QNotified一样要求在commit时删除所有注释？以及是否限制只使用Kotlin进行开发？

**Comment by KyuubiRan** [comment]
1.仅kotlin
2.commit没有太多硬性要求 对commit的内容简单的说明即可
3.不接受一些诸如群发、抢红包之类功能的pr
4.如果有意向加入开发组的话 十分欢迎

**Comment by KyuubiRan** [comment]
另外 对代码的注释也有一定的要求（尤其是工具类）

**Comment by Cryolitia** [comment]
QNotified从来没有要求在commit时删除所有注释
